services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - DB_URI=bolt://neo4j:7687 
    depends_on:
      - neo4j
    volumes:
      - .:/app
      - /app/node_modules
  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP (browser)
      - "7687:7687"   # Bolt (driver)
    environment:
     - NEO4J_AUTH=neo4j/admin001
    - NEO4JLABS_PLUGINS=["apoc"]
    - NEO4J_apoc_ttl_enabled=true
    - NEO4J_apoc_ttl_schedule=10000
    - NEO4J_apoc_ttl_limit=1000
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    - NEO4J_dbms_security_procedures_whitelist=apoc.*
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - db:/data

volumes:
  db:
