FROM node:20-alpine

WORKDIR /app

# Optional: required for native deps
# RUN apk add --no-cache python3 make g++

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Install dev tools
RUN yarn global add tsx typescript tsconfig-paths tsc-alias

COPY tsconfig.prod.json ./tsconfig.prod.json
COPY . .

EXPOSE 8088

CMD ["yarn", "dev"]
