services:
  neo4j:
    image: neo4j:2025.06.2
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP (browser)
      - "7687:7687" # Bolt (driver)
    environment:
      - NEO4J_AUTH=${DB_USERNAME}/${DB_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_ttl_enabled=true
      - NEO4J_apoc_ttl_schedule=60
      - NEO4J_apoc_ttl_limit=5000
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
    volumes:
      - db:/data
      - neo4j_plugins:/plugins
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./src/config/.env
    depends_on:
      - neo4j
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src
          ignore:
            - node_modules/
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: ./src/config/.env

volumes:
  db:
  neo4j_plugins:
