services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./src/config/.env
    environment:
      - DB_URI=bolt://neo4j:7687 
    depends_on:
      - neo4j
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src
          ignore:
            - node_modules/
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: ./src/config/.env

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP (browser)
      - "7687:7687"   # Bolt (driver)
    environment:
      - NEO4J_AUTH=${DB_USERNAME}/${DB_PASSWORD}
    volumes:
      - db:/data

volumes:
  db:
